# Generated by Django 4.2.7 on 2023-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(upload_to='marca_imgs/'),
        ),
    ]
