# Generated by Django 4.2.7 on 2023-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
