# Generated by Django 4.2.7 on 2023-12-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_banner_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_feat_caracteres',
            new_name='destaque',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='product_imgs/'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
